### ISSUE TITLE
trazer problemas TPTP

### ISSUE THREAD

**Issue by arademaker** [own-pt/common-sense-lean#6]
De https://github.com/FredsoNerd/tptp-lean-puzzles para aqui.

**Comment by fredsonaguiar** [comment]
Adicionei os arquivos produzidos em tptp-lean-puzzles ao repositório no último pull request.

**Comment by arademaker** [comment]
Obrigado. Acho que com isso seu repositório pode ser apagado. Vou fechar este issue embora depois eu ainda veja como podemos reorganizar os arquivos.
